command:
  - ${env}
  - C:\REG2025Project_armftn\venv\Scripts\python.exe
  - -m
  - src.train
  - ${args}

program: src/train.py
method: bayes
metric:
  name: avg_val_accuracy
  goal: maximize

parameters:
  model_name:
    value: "clam" # <-- On spécifie que ce sweep est pour CLAM
  
  lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.0005
    
  dropout:
    values: [0.1, 0.25, 0.4]

  weight_decay:
    values: [0.00001, 0.0001, 0.001]